gitSafeReplacementChar: '-'
branchName: '${issue.title,}'

branches:
  - label: feature
    prefix: feature/${issue.number}/
  - label: bug
    prefix: fix/${issue.number}/
  - label: doc
    prefix: doc/${issue.number}/
  - label: '*'
    skip: true
    
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true